### PR TITLE
Handle custom header additions without requiring "Upstash-Forward-*" as a prefix.

### LINKED ISSUE #52: Deleting Schedules Error: Unexpected end of JSON input
Attempting to delete a schedule throws an error `Error: Unexpected end of JSON input` due to a res.json() being expected but not provided by the server. 

In `http.ts` a response is expected `return (await res.json()) as UpstashResponse<TResult>;` but the server does not respond with one, so the above error is thrown.

### PR DESCRIPTION
**Pull request by msywulak**
## Description:
Currently, if you need to send custom headers to a schedule's destination you must prefix them manually with "Upstash-Forward-*". If you forget to add the prefix the headers will be ignored. 

Also, deletion did not work until using new parseResponseAsJson property. 

## Updates

- Handle headers added with or without "Upstash-Forward" while ignoring set property headers. 
- Add `parseResponseAsJson: false,` to schedule deletion. 

## Fixes #52

### CODE REVIEW

**Comment by msywulak** [comment]
Also, if you're alright with the method here or have a cleaner way to do it I could add it to the following as well:

- topics.ts
- client.ts (publish and publishJSON)

Probably could add in `parseResponseAsJson: false,` into a couple of places that need it now.

**Comment by ogzhanolguncu** [comment]
Looks good to me. Since we added failure callback recently this `ignoredHeaders[]` requires an update. Also let's turn this into some sort of utility since we are going to call this in multiple places. And, finally please add an appropriate example similar to `nodejs`example in the example/nodejs repo.

**Comment by msywulak** [comment]
@ogzhanolguncu I haven't made an example yet but is this what you had in mind?

**Comment by ogzhanolguncu** [comment]
Util is looking good. What I have in my mind is [NodeJS Example](https://github.com/upstash/sdk-qstash-ts/tree/main/examples) adding an another example here where you don't need pass `Upstash-Forward-*`. Just to showcase people its possible.

Maybe add another file here[here](https://github.com/upstash/sdk-qstash-ts/blob/main/examples/nodejs/index.js) where you pass optinal headers to your callback.

**Comment by ogzhanolguncu** [comment]
> Also, if you're alright with the method here or have a cleaner way to do it I could add it to the following as well:
> 
> * topics.ts
> * client.ts (publish and publishJSON)
> 
> Probably could add in `parseResponseAsJson: false,` into a couple of places that need it now.

And, let's do this since we now have a easier way to handle this with thanks to`prefixHeaders` func.

**Comment by msywulak** [comment]
About to add the others but I was looking through the API docs and couldn't find a place where you can add custom headers on [topics](https://upstash.com/docs/qstash/api/topics/add-endpoint). I tested a couple of ways but couldn't make it work - trying to see if it was just undocumented but that doesn't look to be the case.

**Comment by ogzhanolguncu** [comment]
The PR is looking good right now. However, I have a concern: what if someone adds a new default header to QStash, and we overlook it or forget to include it here? Since it won't be in the predefined list, it could result in rendering the default header as null, potentially causing issues on the servers.

**Comment by msywulak** [comment]
At the end of the day the client is setting those headers after the util runs, if it was set on the original req, but changed the util up a bit to always ignore any header starting with `"upstash-"` or `"content-type"`. This would make it so you could never set a Upstash specific header using the headers property, but I think that would likely be expected based on the comment for the header property saying that "these headers will be sent to your destination".

**Comment by ogzhanolguncu** [comment]
This is looking much better. I'll test it myself and merge it tomorrow.

**Pull request merged**
